name: auto-aur-update
on:
  workflow_dispatch:
  schedule:
  - cron: "0 */12 * * *"
  

jobs:
  UpdatePkg:
    strategy:
      fail-fast: false
      matrix:
        Packages:
        - clash-verge-bin
        - clash-verge-rev-bin
        - clash-verge-rev-alpha-bin
        - pot-translation
        - pot-translation-bin
        - botgem-electron

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./build-aur-action
        with:
          pkgname: ${{ matrix.Packages }}
          pkgdir: ${{ matrix.Packages }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: ${{ matrix.Packages }}
          pkgbuild: ${{ matrix.Packages }}/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
          allow_empty_commits: false
